### PR TITLE
Added setup script

### PR DESCRIPTION
**Pull request by rvrsh3ll**
Simple setup script if you like.

### CODE REVIEW

**Comment by amarti65** [comment]
Thank you, Will pull down. 

Anthony Martini
mobile: (845)742-4596 tel:845.742.4596
email: amarti65@kent.edu mailto:amarti65@kent.edu
http://www.linkedin.com/in/anthonychristophermartini http://www.linkedin.com/in/anthonychristophermartini

**Comment by kenb123** [comment]
Please add 

apt-get install python3-pip

for pip3 into the sh file and I'll merge the script. It's from the second to last line in the installer checks file.

**Comment by amarti65** [comment]
Are you asking or telling me?

Anthony Martini
mobile: (845)742-4596 tel:845.742.4596
email: amarti65@kent.edu mailto:amarti65@kent.edu
http://www.linkedin.com/in/anthonychristophermartini http://www.linkedin.com/in/anthonychristophermartini

**Comment by rvrsh3ll** [comment]
apt-get install python3-pip is on line 6

**Comment by kenb123** [comment]
Got it! Thanks.

**Pull request merged**
